GET http://localhost:80/users/id?uuid=6159f29f-9f6d-4b01-a022-cb0519a11ddd
Accept: application/json
Cookie: XDEBUG_SESSION=start

###

GET http://localhost:80/users/show?username=admin
Accept: application/json
Cookie: XDEBUG_SESSION=start

###

GET http://localhost:80/posts/id?uuid=72ba514a-5205-4876-a1a2-a16a61c0198a
Accept: application/json
Cookie: XDEBUG_SESSION=start


###

GET http://localhost:80/posts/show?title=Привет
Accept: application/json
Cookie: XDEBUG_SESSION=start

<> 2022-08-16T154619.200.json

###

GET http://localhost:80/comments/id?uuid=41f40601-5b3f-48ba-9530-efa67389227d
Accept: application/json
Cookie: XDEBUG_SESSION=start


###

POST http://localhost:80/posts/create
Accept: application/json
Cookie: XDEBUG_SESSION=start

{
"author_uuid": "10373537-0805-4d7a-830e-22b481b4859c",
"title": "Заголовок для удаления",
"text": "Текст для удаления"
}


###

POST http://localhost:80/comments/create
Accept: application/json
Cookie: XDEBUG_SESSION=start

{
"author_uuid": "a3e78b09-23ae-44fd-9939-865f688894f5",
"post_uuid": "56c541f7-6665-4e67-8e0d-41e544855b6d",
"text": "Мой новый коммент для эшена"
}


###

POST http://localhost:80/posts/delete
Accept: application/json
Cookie: XDEBUG_SESSION=start

{
"uuid": "fd02bf59-8f28-4475-a943-ef59dd12d73f"
}